### ISSUE TITLE
Possible roadmap

### ISSUE THREAD

**Issue by Art4** [simplepie/simplepie#731]
In this issue I collect the progress of the refactoring of SimplePie. This serves roadmap me as a central place for rough planning. Please note that the roadmap is only my personal proposal for the further development of SimplePie, **but has not been officially confirmed by the SimplePie team**.

I would love to hear feedback from the SimplePie team and community. Please share your thoughts on what I think of this roadmap.

## Possible roadmap

All changes in v1.x must be backward compatible to adheres Semantic Versioning. Breaking changes are allowed with the release of v2.

### ✅ SimplePie v1.6.0

- [x] **Merge of #711**.
- [x] Let users try out the new experimantal namespaced classes and collect feedback
- [x] This will also allow us to get a better statistic data about used PHP versions on [packagist.org](https://packagist.org/packages/simplepie/simplepie/php-stats)
- [x] discussion about the necessary changes in `build/compile.php` or the need at all. #725

### 🔲 SimplePie v1.7.0

- [ ] **Merge of #722**.
- [ ] Possibly **raising the minimum PHP version** based on download numbers and feedback, especially from WordPress (ping @rmccue)
- [ ] Copy the tests and change them to test the namespaced classes: #730

### 🔲 SimplePie v1.8.0

- [ ] **Add deprecation warnings** in all classes in `library` folder, see https://github.com/simplepie/simplepie/pull/711#issuecomment-1019526993
- [ ] deprecate the usage of PSR-0
- [ ] deprecate the usage of global constants like `SIMPLEPIE_VERSION`, use `SimplePie\SimplePie::SIMPLEPIE_VERSION` instead
- [ ] possibly deprecate more methods in the `src` folder

### 🔲 SimplePie v2.0.0

- [ ] **remove all deprecated code**
- [ ] remove the `library` folder
- [ ] remove tests for deprecated code
- [ ] Migration to a HTTP library #520 
- [ ] Replace the cache classes with a [PSR-6](https://www.php-fig.org/psr/psr-6/) or [PSR-16](https://www.php-fig.org/psr/psr-16/) implementation

**Comment by Art4** [comment]
The changes for PSR-18 support will take to long, but I would like to release the features for PSR-16 soon. I think it would be better to split the planned features for 1.8.0 into two releases.

**Comment by jtojnar** [comment]
Now that we have raised the minimum version of PHP above 7.0, we could start enabling the [strict type checking](https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict)) internally.  [`@PHP70Migration:risky`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/3969f390a3adbbcdf0acfeadb2e9de7d63efdbba/doc/ruleSets/PHP70MigrationRisky.rst) will do that, though maybe we will need to enable it progressively. Checking with PHPStan will probably be a good idea.

**Comment by Art4** [comment]
> Now that we have raised the minimum version of PHP above 7.0, we could start enabling the [strict type checking](https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict)) internally. [`@PHP70Migration:risky`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/3969f390a3adbbcdf0acfeadb2e9de7d63efdbba/doc/ruleSets/PHP70MigrationRisky.rst) will do that, though maybe we will need to enable it progressively. Checking with PHPStan will probably be a good idea.

Good point. I once tried to enable it everywhere while I was working on #743 and it fails catastrophically. 😅 Thats why I set `'declare_strict_types' => false,` in `.php-cs-fixer.dist.php`. But it would be good to set the strict type at least in all new classes. I will check that and create a PR.

**Comment by jtojnar** [comment]
@Art4 Regarding 1.9.0:

Unfortunately, there were several regressions like https://github.com/simplepie/simplepie/issues/810. We might either want fix all typing issues, possibly with the help of #837, or revert #763 for now.

> * **Allow the usage of [Requests](https://github.com/WordPress/Requests) as HTTP client library**

Do we need explicit support? Can’t the consumer just use [your adapter library](https://packagist.org/packages/art4/requests-psr18-adapter)?

> * **Improve mf2 support**: #684

I would remove it from 1.9 milestone unless we have someone interested in working on this.

**Comment by jtojnar** [comment]
> One could of course use the (relatively new adapter library) but the idea was to check for the existence of Requests and use the library, instead of the deprecated, not maintained File class. This way we could provide a nicer upgrade path without having a new dependency.

To be honest, I do not see the point of introducing whole another `SimplePie\Http\Client` instance, which would basically have to replicate your adapter anyway, just to remove it two releases later when we require PSR-18.

As I see it, the only benefit would be that consumers that already use `Requests` for something else could use a single unified HTTP implementation. But then there would still need to be a way to pass the same options, at which point it is no longer implicit. (I do not think there is any material difference for consumers in whether the adapter is part of SimplePie or a separate library.)

The original roadmap was created when there was no PSR-18 or even HTTPlug so the suggestion for Requests made sense then. But the ecosystem have moved, IMO.

**Comment by mblaney** [comment]
@jtojnar makes a good point @Art4, but if you want to do the extra steps on the roadmap that's fine with me. Otherwise I agree, remove anything that doesn't fit since you originally wrote it.

Is #837 ready to merge? Would be good to get open PRs in then decide if you're both ready for 1.9 or get 1.8.1 out before then.

**Comment by Art4** [comment]
@mblaney @jtojnar I'm totally with you both. I tried to implement PSR-18 in Requests directly (see https://github.com/WordPress/Requests/pull/768) because this would be the best benefit for all. The library was then created from this PR, so the planned Requests implementation in SimplePie is obsolete. I will remove this issue from the roadmap.

For 1.9.0 we should merge #777 (and possible fixes from #826). And I recommend to merge #837 and deprecate the `File` class. (If #777 is merged I can start with the PR). This way we should release 1.9.0 really soon.

**Comment by jtojnar** [comment]
> Is #837 ready to merge?

It is ready from my side, would still be good to get another set of eyes on it in case I missed something.

But as mentioned elsewhere, we need get PHPStan to at least level 8 to detect the `strict_types` errors. There are currently 129 unresolved issues for level 7 and another 55 for level 8. Those would need to be resolved for 1.9.0 if we want to be certain there are no regressions but that can be done later.

**Comment by Art4** [comment]
I moved the some issues like "deprecate the SimplePie\File class" into a new minor release as proposed in #850.
